[features]
seeds = false
[programs.localnet]
chess_game = "2G1pVxGS4p9jFFTVBVirZ2vdQMw22nKfbf6CupVEVZSg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/komo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
